### ISSUE TITLE
os_major is only added if os_minor is also added

### ISSUE THREAD

**Issue by mhunsber** [logstash-plugins/logstash-filter-useragent#65]
The `os_major` field only gets populated if the `os_minor` field is also populated. This makes a lot of the `os_v1_replacement` options in the default regexes.yml file do nothing.

- Version: 3.2.4
- Operating System: Windows
- Config File (if you have sensitive info, please remove it):
```
input {
 stdin {}
}
filter {
 useragent {
  source => 'message' 
  regexes => 'test_regexes.yml' 
 }
}
output {
 stdout {}
}
```
```yaml
user_agent_parsers:
  - regex: (agent)

os_parsers:
   
  - regex: (OS1)
    os_replacement: 'os_name replaced'
    os_v1_replacement: 'os_major replaced'
    
  - regex: (OS2)
    os_replacement: 'os_name replaced'
    os_v1_replacement: 'os_major replaced'
    os_v2_replacement: 'os_minor replaced'

device_parsers:
  - regex: (Device)
```
- Sample Data:
```
[2020-02-17T09:41:16,792][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
OS1
{
    "@timestamp" => 2020-02-17T14:42:11.411Z,
         "build" => "",
          "host" => "micahh-v",
          "name" => "Other",
       "os_name" => "os_name replaced",
            "os" => "os_name replaced",
       "message" => "OS1\r",
        "device" => "Other",
      "@version" => "1"
}
OS2
{
    "@timestamp" => 2020-02-17T14:42:17.304Z,
         "build" => "",
          "name" => "Other",
       "os_name" => "os_name replaced",
        "device" => "Other",
      "@version" => "1",
          "host" => "micahh-v",
            "os" => "os_name replaced",
       "message" => "OS2\r",
      "os_major" => "os_major replaced",
      "os_minor" => "os_minor replaced"
}
```
- Steps to Reproduce:
If you match an os_parser that only has a os_v1_replacement specified. The os_major field will not be populated, but if you match it with one that has both os_v1 and os_v2 specified, both os_major and os_minor will be populated.
